proxy:
  https:
    enabled: false
  # hosts:
  #   - mc-a4.lab.uvalight.net
  # pathSuffix: /jupyter(/|$)(.*)
  # pathType: ImplementationSpecific


hub:
  config:
    Spawner:
      post_stop_hook: |
        def post_stop_hook(spawner):
            import subprocess, os
            # Namespace is usually spawner.namespace
            ns = spawner.namespace
            outdir = "/mnt/data"
            # Call your exporter binary/script that's in the Hub container
            subprocess.Popen([
                "python3",
                "/usr/local/bin/export_scaphandre_metrics.py",
                "--namespace", ns,
                "--output-dir", outdir
            ])
    JupyterHub:
      baseUrl: "/jupyter"
      tornado_settings:
        xheaders: true
    JupyterHubCuller:
      enabled: true
      timeout: 3600 # 1 hour
      every: 6000 # 10 minutes
      concurrency: 10
    Authenticator:
      admin_users:
        - shashikant
        - yuri
        - adnan
        - quint
        - goncalo
    # DummyAuthenticator:
    #   password: greendigit2025
    JupyterHub:
      authenticator_class: dummy
  extraConfig:
    allow-root: |
      from kubespawner import KubeSpawner
      def modify_pod(spawner: KubeSpawner, pod):
          pod.spec.containers[0].security_context = {
              "runAsUser": 0,
              "runAsGroup": 0,
              "privileged": True,
              "allowPrivilegeEscalation": True,
              "capabilities": {
                  "add": ["ALL"]
              }
          }
          return pod
      c.KubeSpawner.modify_pod_hook = modify_pod
  # extraEnv:
  #   HUB_PASSWORD:
  #     valueFrom:
  #       secretKeyRef:
  #         name: hub-password-secret
  #         key: HUB_PASSWORD



singleuser:
  image:
    name: jupyter/datascience-notebook
    tag: latest

  # https://discourse.jupyter.org/t/cannot-use-sudo-have-root-access-using-jupyterhub-with-kubernetes/12548/6
  uid: 0
  fsGid: 0
  # extraEnv:
  #   GRANT_SUDO: "yes" # or "1" in some cases.
  #   NOTEBOOK_ARGS: "--allow-root"


  # extraPodConfig:
  #   automountServiceAccountToken: true
  cmd:
    - bash
    - -c
    - |
      echo "jovyan ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/jovyan && \
      chmod 0440 /etc/sudoers.d/jovyan && \
      exec start.sh jupyterhub-singleuser
  

  # allowPrivilegeEscalation: true
  # # privileged: truee
  # securityContext:
  #   privileged: true
  #   capabilities:
  #     add:
  #       - SYS_ADMIN

  storage:
    type: dynamic
    capacity: 5Gi
    homeMountPath: /home/jovyan
    # dynamic:
    #   storageClass: standard
    #   pvcNameTemplate: claim-{username}
    #   storageAccessModes:
    #     - ReadWriteOnce

    extraVolumes:
      - name: sys
        hostPath:
          path: /sys
          type: Directory

      # - name: proc
      #   hostPath:
      #     path: /proc
      #     type: Directory
  #     - name: containerd-sock
  #       hostPath:
  #         path: /run/containerd/containerd.sock
  #         type: Socket
  #     - name: nginx-config
  #       configMap:
  #         name: scaphandre-nginx-config
  #     - name: default-notebooks
  #       persistentVolumeClaim:
  #         claimName: pvc-default-notebooks

    extraVolumeMounts:
      - name: sys
        mountPath: /sys
        readOnly: true

  #     - name: proc
  #       mountPath: /proc
  #     - name: containerd-sock
  #       mountPath: /run/containerd/containerd.sock
  #       readOnly: true
  #     - name: default-notebooks
  #       mountPath: /home/jovyan/default-notebooks
  #       readOnly: false

