
proxy:
  https:
    enabled: false
  # hosts:
  #   - mc-a4.lab.uvalight.net
  # pathSuffix: /jupyter(/|$)(.*)
  # pathType: ImplementationSpecific


hub:
  config:
    Spawner:
      post_stop_hook: |
        def post_stop_hook(spawner):
            import subprocess, os
            # Namespace is usually spawner.namespace
            ns = spawner.namespace
            outdir = "/mnt/data"
            # Call your exporter binary/script that's in the Hub container
            subprocess.Popen([
                "python3",
                "/usr/local/bin/export_scaphandre_metrics.py",
                "--namespace", ns,
                "--output-dir", outdir
            ])
    JupyterHub:
      baseUrl: "/jupyter"
      tornado_settings:
        xheaders: true
    JupyterHubCuller:
      enabled: true
      timeout: 3600 # 1 hour
      every: 6000 # 10 minutes
      concurrency: 10
    Authenticator:
      admin_users:
        - shashikant
        - yuri
        - adnan
        - quint
        - goncalo
    JupyterHub:
      authenticator_class: dummy

singleuser:
  image:
    name: jupyter/datascience-notebook
    tag: latest

  storage:
    type: dynamic
    capacity: 5Gi
    homeMountPath: /home/jovyan
    dynamic:
      storageClass: standard
      pvcNameTemplate: claim-{username}
      storageAccessModes:
        - ReadWriteOnce

    extraVolumes:
      - name: powercap
        hostPath:
          path: /sys/class/powercap
          type: Directory
      - name: proc
        hostPath:
          path: /proc
          type: Directory
      - name: containerd-sock
        hostPath:
          path: /run/containerd/containerd.sock
          type: Socket
      - name: nginx-config
        configMap:
          name: scaphandre-nginx-config
      - name: default-notebooks
        persistentVolumeClaim:
          claimName: pvc-default-notebooks

    extraVolumeMounts:
      # - name: export-script
      #   mountPath: /usr/local/bin/export_metrics.py
      #   subPath: export_metrics.py
      #   readOnly: true
      - name: powercap
        mountPath: /sys/class/powercap
      - name: proc
        mountPath: /proc
      - name: containerd-sock
        mountPath: /run/containerd/containerd.sock
        readOnly: true
      - name: default-notebooks
        mountPath: /home/jovyan/default-notebooks
        readOnly: false


  extraContainers:
    - name: scaphandre
      image: hubblo/scaphandre:latest
      args:
        - prometheus
        - "--address=0.0.0.0"
        - "--port=8080"
        - "--containers"
      ports:
        - name: rawmetrics
          containerPort: 8080

    - name: proxy-metrics
      image: nginx:stable-alpine
      volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/conf.d
      ports:
        - name: metrics
          containerPort: 8081
  
  uid: 0
  allowPrivilegeEscalation: true
  cmd: null
  extraEnv:
    GRANT_SUDO: "1"
    NOTEBOOK_ARGS: "--allow-root"

