proxy:
  https:
    enabled: false

hub:
  config:
    JupyterHub:
      baseUrl: "/jupyter"
      tornado_settings:
        xheaders: true
    JupyterHubCuller:
      enabled: true
      timeout: 3600 # 1 hour
      every: 6000 # 10 minutes
      concurrency: 10
    Authenticator:
      admin_users:
        - shashikant
        - yuri
        - adnan
        - quint
        - goncalo
        - ana
        - kilian
        - edouard
    JupyterHub:
      authenticator_class: dummy
  extraConfig:
    enable-api-accces: |
      c.KubeSpawner.automount_serviceaccount_token = True
    allow-root: |
      from kubespawner import KubeSpawner
      def modify_pod(spawner: KubeSpawner, pod):
          pod.spec.containers[0].security_context = {
              "runAsUser": 0,
              "runAsGroup": 0,
              "privileged": True,
              "allowPrivilegeEscalation": True,
              "capabilities": {
                  "add": ["ALL"]
              }
          }
          return pod
      c.KubeSpawner.modify_pod_hook = modify_pod



singleuser:
  image:
    name: jupyter/datascience-notebook
    tag: latest
  
  extraEnv:
    GRANT_SUDO: "yes"
    NOTEBOOK_ARGS: "--allow-root"

  uid: 0
  fsGid: 0
  cmd:
    - bash
    - -c
    - |
      echo "jovyan ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/jovyan && \
      chmod 0440 /etc/sudoers.d/jovyan && \
      exec start.sh jupyterhub-singleuser
  
  extraPodConfig:
    automountServiceAccountToken: true

  storage:
    type: dynamic
    homeMountPath: /home/jovyan
    # capacity: 5Gi
    # dynamic:
    #   storageClass: standard
    #   pvcNameTemplate: claim-{username}
    #   storageAccessModes:
    #     - ReadWriteOnce

    extraVolumes:
      - name: sys
        hostPath:
          path: /sys
          type: Directory

    extraVolumeMounts:
      - name: sys
        mountPath: /sys
        readOnly: true
