apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: jhub-scaphandre
  namespace: monitoring
  labels:
    release: prometheus-grafana
spec:
  selector:
    matchLabels:
      component: singleuser-server
  namespaceSelector:
    matchNames:
      - jhub
  podMetricsEndpoints:
    - port: metrics
      path: /metrics
      interval: 5s
      scheme: http
      followRedirects: true
      fallbackScrapeProtocol: PrometheusText0.0.4
