apiVersion: v1
kind: Pod
metadata:
  name: pvc-loader
  namespace: jhub
spec:
  containers:
    - name: pvc-loader
      image: busybox
      command: ["sleep", "3600"] 
      volumeMounts:
        - name: notebook-pvc
          mountPath: /mnt
  volumes:
    - name: notebook-pvc
      persistentVolumeClaim:
        claimName: shashikant-notebook-pvc
  restartPolicy: Never
