proxy:
 https:
   enabled: false

hub:
  config:
    JupyterHub:
      tornado_settings:
        xheaders: true
    Authenticator:
      admin_users:
        - shashikant
        - yuri
        - adnan
        - quint
        - goncalo
    DummyAuthenticator:
      password: greendigit2025
    JupyterHub:
      authenticator_class: dummy


singleuser:
  #  app: jupyterhub # <- the label must be matching with the podmonitor in scaphandre.
  image:
    name: jupyter/datascience-notebook
    tag: latest
  # extraPodConfig:
  #   volumes:
  #     - name: powercap
  #       hostPath:
  #         path: /sys/class/powercap
  #         type: Directory
    # securityContext:
    #   capabilities:
    #     add: ["SYS_RAWIO"]
  extraContainers:
    - name: scaphandre
      image: hubblo/scaphandre
      args:
        - prometheus
      # volumeMounts:
      #   - name: powercap
      #     mountPath: /sys/class/powercap
  #     # command: ["/bin/sh"]
  #     # args:
  #     #   - "-c"
  #     #   - >-
  #     #     cgroup_path=$(awk -F: '/cpu/ ${print $3}' /proc/self/cgroup || echo "/") && exec scaphandre prometheus --cgroup "$cgroup_path"
  #     # args:
  #     #   - "-c"
  #     #   - |
  #     #     cgroup_path=$(awk -F: '/cpu/ {print $3}' /proc/self/cgroup)
  #     #     exec scaphandre prometheus --cgroup "$cgroup_path"
      # ports:
      #   - name: prometheus
      #     containerPort: 8080
  #     volumeMounts:
  #       - name: powercap
  #         mountPath: /sys/class/powercap
